<!-- Copyright (C) 2011 The Libphonenumber Authors

     Licensed under the Apache License, Version 2.0 (the "License");
     you may not use this file except in compliance with the License.
     You may obtain a copy of the License at

     http://www.apache.org/licenses/LICENSE-2.0

     Unless required by applicable law or agreed to in writing, software
     distributed under the License is distributed on an "AS IS" BASIS,
     WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
     See the License for the specific language governing permissions and
     limitations under the License.

     @author: Lara Rennie
     @author: Shaopeng Jia

     Additional Phone Number Formatting information, containing alternative
     formats that are commonly used when writing phone numbers in certain
     countries. Note that this is in addition to the formatting information
     provided by the main PhoneNumberMetadata.xml file - formatting patterns
     should not be duplicated.

     Note also that only the most specific leading-digits pattern is present for
     each pattern - the less specific ones are used only by the
     AsYouTypeFormatter, and the AsYouTypeFormatter does not require information
     on alternate formatting patterns.

     For regions that share a country calling code, only the region with
     mainCountryForCode set to true in PhoneNumberMetadata.xml should be present
     here.

     Note: Territories are in alphabetical order by their IDs, which are based on CLDR
           two-letter region codes (or are set to "001" for non-geographical entities, which
           represents "World" in the UN M.49 standard). The country names in the comments are the
           official short names in English according to CLDR.

     For more information on what each element represents, see resources/phonemetadata.proto
-->

<!DOCTYPE phoneNumberMetadata [
    <!ELEMENT phoneNumberMetadata (territories)>
    <!ELEMENT territories (territory+)>
    <!ELEMENT territory (availableFormats)>
    <!ELEMENT availableFormats (numberFormat+)>
    <!ELEMENT numberFormat (leadingDigits*, format, intlFormat*)>
    <!ELEMENT leadingDigits (#PCDATA)>
    <!ELEMENT format (#PCDATA)>
    <!ELEMENT intlFormat (#PCDATA)>

    <!ATTLIST territory countryCode CDATA #REQUIRED>
    <!ATTLIST territory nationalPrefix CDATA #IMPLIED>
    <!ATTLIST numberFormat nationalPrefixFormattingRule CDATA #IMPLIED>
    <!ATTLIST numberFormat pattern CDATA #REQUIRED>
]>

<phoneNumberMetadata>
  <territories>
    <!-- Germany (DE) -->
    <territory countryCode="49">
      <availableFormats>
        <numberFormat pattern="(\d{2})(\d{3})(\d{3,4})">
          <leadingDigits>
            [34]0|
            [68]9
          </leadingDigits>
          <format>$1 $2 $3</format>
        </numberFormat>
        <!-- Sometimes four-digit area codes are split into two groups of two. -->
        <numberFormat pattern="(\d{2})(\d{2})(\d{2})(\d{2})(\d{2})">
          <leadingDigits>
            2(?:
              0[4-6]|
              1(?:
                [035-9]|
                29
              )|
              3[0235-9]|
              7[2-7]
            )|
            3(?:
              0|
              3(?:
                0[1-467]|
                2[127-9]|
                3[124578]|
                7[1257-9]|
                8[1256]|
                9[145]
              )|
              4(?:
                2[135]|
                4[13578]|
                9[1346]
              )|
              5(?:
                0[14]|
                2[1-3589]|
                6[1-4]|
                7[13468]|
                8[13568]
              )|
              6(?:
                2[1-489]|
                3[124-6]|
                6[13]|
                7[12579]|
                8[1-356]|
                9[135]
              )|
              7(?:
                2[1-7]|
                4[145]|
                6[1-5]|
                7[1-4]
              )|
              8(?:
                21|
                6|
                7[1467]|
                8[136]
              )|
              9(?:
                0[12479]|
                2[1358]|
                4[134679]|
                6[1-9]|
                7[136]|
                8[147]
              )
            )|
            4[01]|
            50|
            6[09]|
            7(?:
              0|
              8[02-5]|
              9[03-7]
            )|
            8(?:
              3[02-46-9]|
              5[03-9]|
              6[2-8]|
              8[024-6]|
              9
            )|
            9(?:
              0[7-9]|
              7[02-467]
            )|
            (?:
              45|
              84
            )[02-6]|
            3(?:
              83|
              99
            )[1468]|
            3[68]4[1347]|
            3(?:
              47|
              60
            )[1356]|
            (?:
              66|
              71|
              80
            )[2-9]|
            3(?:
              3[46]|
              46|
              5[49]
            )[1246]|
            (?:
              22|
              47|
              81
            )[02-79]|
            3[4579]3[1357]|
            (?:
              28|
              49|
              5[79]|
              7[27]|
              9[589]
            )[02-7]|
            (?:
              2[569]|
              4[2-48]|
              5[124-6]|
              6[1-358]|
              73|
              82|
              9[1-4]
            )[02-9]|
            (?:
              24|
              [49]6|
              5[38]|
              6[47]|
              7[4-6]|
              87
            )[02-8]
          </leadingDigits>
          <format>$1 $2 $3 $4 $5</format>
        </numberFormat>
        <numberFormat pattern="(\d{2})(\d{4})(\d{3,4})">
          <leadingDigits>
            [34]0|
            [68]9
          </leadingDigits>
          <format>$1 $2 $3</format>
        </numberFormat>
        <numberFormat pattern="(\d{2})(\d{3})(\d{2})(\d{1,2})">
          <leadingDigits>
            [34]0|
            [68]9
          </leadingDigits>
          <format>$1 $2 $3 $4</format>
        </numberFormat>
        <numberFormat pattern="(\d{2})(\d{3})(\d{3})(\d{2,3})">
          <leadingDigits>
            3[02]|
            40|
            [68]9
          </leadingDigits>
          <format>$1 $2 $3 $4</format>
        </numberFormat>
        <numberFormat pattern="(\d{2})(\d{2})(\d{2})(\d)(\d{2})(\d{2})">
          <leadingDigits>
            3[02]|
            40|
            [68]9
          </leadingDigits>
          <format>$1 $2 $3 $4 $5 $6</format>
        </numberFormat>
        <numberFormat pattern="(\d{3})(\d{3})(\d{2,4})">
          <leadingDigits>
            2(?:
              0[1-389]|
              12[0-8]
            )|
            3(?:
              [35-9][15]|
              4[015]
            )|
            906|
            2(?:
              [13][14]|
              2[18]
            )|
            (?:
              2[4-9]|
              4[2-9]|
              [579][1-9]|
              [68][1-8]
            )1
          </leadingDigits>
          <format>$1 $2 $3</format>
        </numberFormat>
        <numberFormat pattern="(\d{3})(\d{4})(\d{3,4})">
          <leadingDigits>
            2(?:
              0[1-389]|
              12[0-8]
            )|
            3(?:
              [35-9][15]|
              4[015]
            )|
            906|
            2(?:
              [13][14]|
              2[18]
            )|
            (?:
              2[4-9]|
              4[2-9]|
              [579][1-9]|
              [68][1-8]
            )1
          </leadingDigits>
          <format>$1 $2 $3</format>
        </numberFormat>
        <numberFormat pattern="(\d{3})(\d{2})(\d{2})(\d{1,2})">
          <leadingDigits>
            2(?:
              0[1-389]|
              12[0-8]
            )|
            3(?:
              [35-9][15]|
              4[015]
            )|
            906|
            2(?:
              [13][14]|
              2[18]
            )|
            (?:
              2[4-9]|
              4[2-9]|
              [579][1-9]|
              [68][1-8]
            )1
          </leadingDigits>
          <format>$1 $2 $3 $4</format>
        </numberFormat>
        <numberFormat pattern="(\d{3})(\d{2})(\d{2})(\d{2})(\d{2})">
          <leadingDigits>
            2(?:
              0[1-389]|
              12[0-8]
            )|
            3(?:
              [35-9][15]|
              4[015]
            )|
            906|
            2(?:
              [13][14]|
              2[18]
            )|
            (?:
              2[4-9]|
              4[2-9]|
              [579][1-9]|
              [68][1-8]
            )1
          </leadingDigits>
          <format>$1 $2 $3 $4 $5</format>
        </numberFormat>
        <numberFormat pattern="(\d{3})(\d{3})(\d{2})(\d{2})">
          <leadingDigits>
            2(?:
              0[1-389]|
              12[0-8]
            )|
            3(?:
              [35-9][15]|
              4[015]
            )|
            906|
            2(?:
              [13][14]|
              2[18]
            )|
            (?:
              2[4-9]|
              4[2-9]|
              [579][1-9]|
              [68][1-8]
            )1
          </leadingDigits>
          <format>$1 $2 $3 $4</format>
        </numberFormat>
        <numberFormat pattern="(\d{3})(\d{3})(\d{2})(\d{2})(\d)">
          <leadingDigits>
            2(?:
              0[1-389]|
              12[0-8]
            )|
            3(?:
              [35-9][15]|
              4[015]
            )|
            906|
            2(?:
              [13][14]|
              2[18]
            )|
            (?:
              2[4-9]|
              4[2-9]|
              [579][1-9]|
              [68][1-8]
            )1
          </leadingDigits>
          <format>$1 $2 $3 $4 $5</format>
        </numberFormat>
        <numberFormat pattern="(\d{3})(\d{3})(\d{3})(\d{2,3})">
          <leadingDigits>
            2(?:
              0[1-389]|
              12[0-8]
            )|
            3(?:
              [35-9][15]|
              4[015]
            )|
            906|
            2(?:
              [13][14]|
              2[18]
            )|
            (?:
              2[4-9]|
              4[2-9]|
              [579][1-9]|
              [68][1-8]
            )1
          </leadingDigits>
          <format>$1 $2 $3 $4</format>
        </numberFormat>
        <numberFormat pattern="(\d{4})(\d{3})(\d{1,4})">
          <leadingDigits>
            2(?:
              0[4-6]|
              1(?:
                [035-9]|
                29
              )|
              3[0235-9]|
              7[2-7]
            )|
            3(?:
              3(?:
                0[1-467]|
                2[127-9]|
                3[124578]|
                7[1257-9]|
                8[1256]|
                9[145]
              )|
              4(?:
                2[135]|
                4[13578]|
                9[1346]
              )|
              5(?:
                0[14]|
                2[1-3589]|
                6[1-4]|
                7[13468]|
                8[13568]
              )|
              6(?:
                2[1-489]|
                3[124-6]|
                6[13]|
                7[12579]|
                8[1-356]|
                9[135]
              )|
              7(?:
                2[1-7]|
                4[145]|
                6[1-5]|
                7[1-4]
              )|
              8(?:
                21|
                6|
                7[1467]|
                8[136]
              )|
              9(?:
                0[12479]|
                2[1358]|
                4[134679]|
                6[1-9]|
                7[136]|
                8[147]
              )
            )|
            41|
            [56]0|
            7(?:
              0[2-8]|
              8[02-5]|
              9[03-7]
            )|
            8(?:
              3[02-46-9]|
              5[03-9]|
              6[2-8]|
              8[024-6]
            )|
            9(?:
              0[7-9]|
              7[02-467]
            )|
            (?:
              45|
              84
            )[02-6]|
            3(?:
              83|
              99
            )[1468]|
            3[68]4[1347]|
            3(?:
              47|
              60
            )[1356]|
            (?:
              66|
              71|
              80
            )[2-9]|
            3(?:
              3[46]|
              46|
              5[49]
            )[1246]|
            (?:
              22|
              47|
              81
            )[02-79]|
            3[4579]3[1357]|
            (?:
              28|
              49|
              5[79]|
              7[27]|
              9[589]
            )[02-7]|
            (?:
              2[569]|
              4[2-48]|
              5[124-6]|
              6[1-358]|
              73|
              82|
              9[1-4]
            )[02-9]|
            (?:
              24|
              [49]6|
              5[38]|
              6[47]|
              7[4-6]|
              87
            )[02-8]
          </leadingDigits>
          <format>$1 $2 $3</format>
        </numberFormat>
        <!-- Sometimes four-digit area codes are split into two groups of two. -->
        <numberFormat pattern="(\d{2})(\d{2})(\d{2})(\d{2})">
          <leadingDigits>
            2(?:
              0[4-6]|
              1(?:
                [035-9]|
                29
              )|
              3[0235-9]|
              7[2-7]
            )|
            3(?:
              3(?:
                0[1-467]|
                2[127-9]|
                3[124578]|
                7[1257-9]|
                8[1256]|
                9[145]
              )|
              4(?:
                2[135]|
                4[13578]|
                9[1346]
              )|
              5(?:
                0[14]|
                2[1-3589]|
                6[1-4]|
                7[13468]|
                8[13568]
              )|
              6(?:
                2[1-489]|
                3[124-6]|
                6[13]|
                7[12579]|
                8[1-356]|
                9[135]
              )|
              7(?:
                2[1-7]|
                4[145]|
                6[1-5]|
                7[1-4]
              )|
              8(?:
                21|
                6|
                7[1467]|
                8[136]
              )|
              9(?:
                0[12479]|
                2[1358]|
                4[134679]|
                6[1-9]|
                7[136]|
                8[147]
              )
            )|
            41|
            66[2-9]|
            7(?:
              1[2-9]|
              8[02-5]|
              9[03-7]
            )|
            8(?:
              3[02-46-9]|
              5[03-9]|
              6[2-8]|
              8[024-6]
            )|
            9(?:
              0[7-9]|
              7[02-467]
            )|
            [5-8]0|
            (?:
              45|
              84
            )[02-6]|
            3(?:
              83|
              99
            )[1468]|
            3[68]4[1347]|
            3(?:
              47|
              60
            )[1356]|
            3(?:
              3[46]|
              46|
              5[49]
            )[1246]|
            (?:
              22|
              47|
              81
            )[02-79]|
            3[4579]3[1357]|
            (?:
              28|
              49|
              5[79]|
              7[27]|
              9[589]
            )[02-7]|
            (?:
              2[569]|
              4[2-48]|
              5[124-6]|
              6[1-358]|
              73|
              82|
              9[1-4]
            )[02-9]|
            (?:
              24|
              [49]6|
              5[38]|
              6[47]|
              7[4-6]|
              87
            )[02-8]
          </leadingDigits>
          <format>$1 $2 $3 $4</format>
        </numberFormat>
        <!-- Sometimes four-digit area codes are split into two groups of two. -->
        <numberFormat pattern="(\d{2})(\d{2})(\d)(\d{2})(\d{2})">
          <leadingDigits>
            2(?:
              0[4-6]|
              1(?:
                [035-9]|
                29
              )|
              3[0235-9]|
              7[2-7]
            )|
            3(?:
              3(?:
                0[1-467]|
                2[127-9]|
                3[124578]|
                7[1257-9]|
                8[1256]|
                9[145]
              )|
              4(?:
                2[135]|
                4[13578]|
                9[1346]
              )|
              5(?:
                0[14]|
                2[1-3589]|
                6[1-4]|
                7[13468]|
                8[13568]
              )|
              6(?:
                2[1-489]|
                3[124-6]|
                6[13]|
                7[12579]|
                8[1-356]|
                9[135]
              )|
              7(?:
                2[1-7]|
                4[145]|
                6[1-5]|
                7[1-4]
              )|
              8(?:
                21|
                6|
                7[1467]|
                8[136]
              )|
              9(?:
                0[12479]|
                2[1358]|
                4[134679]|
                6[1-9]|
                7[136]|
                8[147]
              )
            )|
            41|
            66[2-9]|
            7(?:
              1[2-9]|
              8[02-5]|
              9[03-7]
            )|
            8(?:
              3[02-46-9]|
              5[03-9]|
              6[2-8]|
              8[024-6]
            )|
            9(?:
              0[7-9]|
              7[02-467]
            )|
            [5-8]0|
            (?:
              45|
              84
            )[02-6]|
            3(?:
              83|
              99
            )[1468]|
            3[68]4[1347]|
            3(?:
              47|
              60
            )[1356]|
            3(?:
              3[46]|
              46|
              5[49]
            )[1246]|
            (?:
              22|
              47|
              81
            )[02-79]|
            3[4579]3[1357]|
            (?:
              28|
              49|
              5[79]|
              7[27]|
              9[589]
            )[02-7]|
            (?:
              2[569]|
              4[2-48]|
              5[124-6]|
              6[1-358]|
              73|
              82|
              9[1-4]
            )[02-9]|
            (?:
              24|
              [49]6|
              5[38]|
              6[47]|
              7[4-6]|
              87
            )[02-8]
          </leadingDigits>
          <format>$1 $2 $3 $4 $5</format>
        </numberFormat>
        <!-- Sometimes four-digit area codes are split into two groups of two. -->
        <numberFormat pattern="(\d{2})(\d{2})(\d)(\d{2})(\d{2})(\d{2})">
          <leadingDigits>
            2(?:
              0[4-6]|
              1(?:
                [035-9]|
                29
              )|
              3[0235-9]|
              7[2-7]
            )|
            3(?:
              3(?:
                0[1-467]|
                2[127-9]|
                3[124578]|
                7[1257-9]|
                8[1256]|
                9[145]
              )|
              4(?:
                2[135]|
                4[13578]|
                9[1346]
              )|
              5(?:
                0[14]|
                2[1-3589]|
                6[1-4]|
                7[13468]|
                8[13568]
              )|
              6(?:
                2[1-489]|
                3[124-6]|
                6[13]|
                7[12579]|
                8[1-356]|
                9[135]
              )|
              7(?:
                2[1-7]|
                4[145]|
                6[1-5]|
                7[1-4]
              )|
              8(?:
                21|
                6|
                7[1467]|
                8[136]
              )|
              9(?:
                0[12479]|
                2[1358]|
                4[134679]|
                6[1-9]|
                7[136]|
                8[147]
              )
            )|
            41|
            [56]0|
            7(?:
              0[2-8]|
              8[02-5]|
              9[03-7]
            )|
            8(?:
              3[02-46-9]|
              5[03-9]|
              6[2-8]|
              8[024-6]
            )|
            9(?:
              0[7-9]|
              7[02-467]
            )|
            (?:
              45|
              84
            )[02-6]|
            3(?:
              83|
              99
            )[1468]|
            3[68]4[1347]|
            3(?:
              47|
              60
            )[1356]|
            (?:
              66|
              71|
              80
            )[2-9]|
            3(?:
              3[46]|
              46|
              5[49]
            )[1246]|
            (?:
              22|
              47|
              81
            )[02-79]|
            3[4579]3[1357]|
            (?:
              28|
              49|
              5[79]|
              7[27]|
              9[589]
            )[02-7]|
            (?:
              2[569]|
              4[2-48]|
              5[124-6]|
              6[1-358]|
              73|
              82|
              9[1-4]
            )[02-9]|
            (?:
              24|
              [49]6|
              5[38]|
              6[47]|
              7[4-6]|
              87
            )[02-8]
          </leadingDigits>
          <format>$1 $2 $3 $4 $5 $6</format>
        </numberFormat>
        <!-- Sometimes four-digit area codes are split into two groups of two. -->
        <numberFormat pattern="(\d{2})(\d{2})(\d{2})(\d{2})(\d{2})(\d{2})">
          <leadingDigits>
            2(?:
              0[4-6]|
              1(?:
                [035-9]|
                29
              )|
              3[0235-9]|
              7[2-7]
            )|
            3(?:
              3(?:
                0[1-467]|
                2[127-9]|
                3[124578]|
                7[1257-9]|
                8[1256]|
                9[145]
              )|
              4(?:
                2[135]|
                4[13578]|
                9[1346]
              )|
              5(?:
                0[14]|
                2[1-3589]|
                6[1-4]|
                7[13468]|
                8[13568]
              )|
              6(?:
                2[1-489]|
                3[124-6]|
                6[13]|
                7[12579]|
                8[1-356]|
                9[135]
              )|
              7(?:
                2[1-7]|
                4[145]|
                6[1-5]|
                7[1-4]
              )|
              8(?:
                21|
                6|
                7[1467]|
                8[136]
              )|
              9(?:
                0[12479]|
                2[1358]|
                4[134679]|
                6[1-9]|
                7[136]|
                8[147]
              )
            )|
            41|
            7(?:
              8[02-5]|
              9[03-7]
            )|
            8(?:
              3[02-46-9]|
              5[03-9]|
              6[2-8]|
              8[024-6]
            )|
            9(?:
              0[7-9]|
              7[02-467]
            )|
            [5-7]0|
            (?:
              45|
              84
            )[02-6]|
            3(?:
              83|
              99
            )[1468]|
            3[68]4[1347]|
            3(?:
              47|
              60
            )[1356]|
            (?:
              66|
              71|
              80
            )[2-9]|
            3(?:
              3[46]|
              46|
              5[49]
            )[1246]|
            (?:
              22|
              47|
              81
            )[02-79]|
            3[4579]3[1357]|
            (?:
              28|
              49|
              5[79]|
              7[27]|
              9[589]
            )[02-7]|
            (?:
              2[569]|
              4[2-48]|
              5[124-6]|
              6[1-358]|
              73|
              82|
              9[1-4]
            )[02-9]|
            (?:
              24|
              [49]6|
              5[38]|
              6[47]|
              7[4-6]|
              87
            )[02-8]
          </leadingDigits>
          <format>$1 $2 $3 $4 $5 $6</format>
        </numberFormat>
        <numberFormat pattern="(\d{4})(\d{4})(\d{1,4})">
          <leadingDigits>
            2(?:
              0[4-6]|
              1(?:
                [035-9]|
                29
              )|
              3[0235-9]|
              7[2-7]
            )|
            3(?:
              3(?:
                0[1-467]|
                2[127-9]|
                3[124578]|
                7[1257-9]|
                8[1256]|
                9[145]
              )|
              4(?:
                2[135]|
                4[13578]|
                9[1346]
              )|
              5(?:
                0[14]|
                2[1-3589]|
                6[1-4]|
                7[13468]|
                8[13568]
              )|
              6(?:
                2[1-489]|
                3[124-6]|
                6[13]|
                7[12579]|
                8[1-356]|
                9[135]
              )|
              7(?:
                2[1-7]|
                4[145]|
                6[1-5]|
                7[1-4]
              )|
              8(?:
                21|
                6|
                7[1467]|
                8[136]
              )|
              9(?:
                0[12479]|
                2[1358]|
                4[134679]|
                6[1-9]|
                7[136]|
                8[147]
              )
            )|
            41|
            [56]0|
            7(?:
              0[2-8]|
              8[02-5]|
              9[03-7]
            )|
            8(?:
              3[02-46-9]|
              5[03-9]|
              6[2-8]|
              8[024-6]
            )|
            9(?:
              0[7-9]|
              7[02-467]
            )|
            (?:
              45|
              84
            )[02-6]|
            3(?:
              83|
              99
            )[1468]|
            3[68]4[1347]|
            3(?:
              47|
              60
            )[1356]|
            (?:
              66|
              71|
              80
            )[2-9]|
            3(?:
              3[46]|
              46|
              5[49]
            )[1246]|
            (?:
              22|
              47|
              81
            )[02-79]|
            3[4579]3[1357]|
            (?:
              28|
              49|
              5[79]|
              7[27]|
              9[589]
            )[02-7]|
            (?:
              2[569]|
              4[2-48]|
              5[124-6]|
              6[1-358]|
              73|
              82|
              9[1-4]
            )[02-9]|
            (?:
              24|
              [49]6|
              5[38]|
              6[47]|
              7[4-6]|
              87
            )[02-8]
          </leadingDigits>
          <format>$1 $2 $3</format>
        </numberFormat>
        <numberFormat pattern="(\d{4})(\d{3})(\d{3})(\d{3})">
          <leadingDigits>
            2(?:
              0[4-6]|
              1(?:
                [035-9]|
                29
              )|
              3[0235-9]|
              7[2-7]
            )|
            3(?:
              3(?:
                0[1-467]|
                2[127-9]|
                3[124578]|
                7[1257-9]|
                8[1256]|
                9[145]
              )|
              4(?:
                2[135]|
                4[13578]|
                9[1346]
              )|
              5(?:
                0[14]|
                2[1-3589]|
                6[1-4]|
                7[13468]|
                8[13568]
              )|
              6(?:
                2[1-489]|
                3[124-6]|
                6[13]|
                7[12579]|
                8[1-356]|
                9[135]
              )|
              7(?:
                2[1-7]|
                4[145]|
                6[1-5]|
                7[1-4]
              )|
              8(?:
                21|
                6|
                7[1467]|
                8[136]
              )|
              9(?:
                0[12479]|
                2[1358]|
                4[134679]|
                6[1-9]|
                7[136]|
                8[147]
              )
            )|
            4[19]|
            7(?:
              8[02-5]|
              9[03-7]
            )|
            8(?:
              3[02-46-9]|
              5[03-9]|
              6[2-8]|
              8[024-6]
            )|
            9(?:
              0[7-9]|
              7[02-467]
            )|
            [5-7]0|
            (?:
              45|
              84
            )[02-6]|
            3(?:
              83|
              99
            )[1468]|
            3[68]4[1347]|
            3(?:
              47|
              60
            )[1356]|
            (?:
              66|
              71|
              80
            )[2-9]|
            3(?:
              3[46]|
              46|
              5[49]
            )[1246]|
            (?: